version: '3.8'

services:
  postgres:
    image: postgres:13.5
    # container_name: my_postgres_13_5
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb            # <-- рекомендую явно задать
      TZ: UTC
    ports:
      - "5434:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  postgres:
